services:
#    riad_mazal_riad_mazal.example:
#        class: Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.locale_listener:
        class: RiadMazal\RiadMazalBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
